# Azure Pipeline Template for ML Workspace Resources Deployment
parameters:
- name: environment
  type: string
  default: dev
- name: serviceConnection
  type: string

jobs:
- deployment: DeployMLResources
  displayName: Deploy ML Resources
  pool:
    vmImage: ubuntu-16.04
  environment: ${{ parameters.environment }}
  variables:
  - name: resourceGroupName
    value: amlquickstart-${{ parameters.environment }}
  - name: resourceGroupLocation
    value: westeurope
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: infratemplates
        - script: ls
          displayName: 'List dirs'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Storage'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
            csmFile: '$(Pipeline.Workspace)/infratemplates/storage/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/storage/parameters.json'
            overrideParameters: |
              -environment "${{ parameters.environment }}"

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Container Registry'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
            csmFile: '$(Pipeline.Workspace)/infratemplates/containerregistry/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/containerregistry/parameters.json'
            overrideParameters: |
              -environment "${{ parameters.environment }}"

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Application Insights'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
            csmFile: '$(Pipeline.Workspace)/infratemplates/appinsights/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/appinsights/parameters.json'
            overrideParameters: |
              -environment "${{ parameters.environment }}"

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Key Vault'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
            csmFile: '$(Pipeline.Workspace)/infratemplates/keyvault/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/keyvault/parameters.json'
            overrideParameters: |
              -environment "${{ parameters.environment }}"

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy ML Workspace'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
            csmFile: '$(Pipeline.Workspace)/infratemplates/mlworkspace/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/mlworkspace/parameters.json'
            overrideParameters: |
              -environment "${{ parameters.environment }}"

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy ML Compute'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
            csmFile: '$(Pipeline.Workspace)/infratemplates/mlcompute/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/mlcompute/parameters.json'
            overrideParameters: |
              -environment "${{ parameters.environment }}"
